jenkins:
  version: prod

spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
